# Node.js
# Build a general Node.js application with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/javascript
jobs:
  - job: Build
    pool:
      name: Hosted Ubuntu 1604
      demands: npm
    steps:
      - task: NodeTool@0
        displayName: "Use Node 10"
        inputs:
          versionSpec: 10.x
      - task: Npm@1
        displayName: "Install dev dependencies"
        inputs:
          verbose: false
      - task: Npm@1
        displayName: "Install client dependencies"
        inputs:
          verbose: false
          workingDir: client
      - task: Npm@1
        displayName: "Install server dependencies"
        inputs:
          verbose: false
          workingDir: server
      - task: Npm@1
        displayName: "build the extension"
        inputs:
          command: custom
          customCommand: "run build"
          verbose: false
      - task: PublishPipelineArtifact@0
        inputs:
          artifactName: "GherkinEditor"
          targetPath: client/out
      - task: PublishPipelineArtifact@0
        inputs:
          artifactName: "GherkinServer"
          targetPath: server/out

  - job: Windows
    dependsOn: Build
    pool:
      name: Hosted VS2017
      demands: npm
    steps:
      - task: NodeTool@0
        displayName: "Use Node 10"
        inputs:
          versionSpec: 10.x
      - task: Npm@1
        displayName: "Install dev dependencies"
        inputs:
          verbose: false
      - task: Npm@1
        displayName: "Install client dependencies"
        inputs:
          verbose: false
          workingDir: client
      - task: Npm@1
        displayName: "Install server dependencies"
        inputs:
          verbose: false
          workingDir: server
      - task: DownloadPipelineArtifact@0
        inputs:
          artifactName: "GherkinEditor"
          targetPath: $(Build.Repository.LocalPath)/client/out
      - task: DownloadPipelineArtifact@0
        inputs:
          artifactName: "GherkinServer"
          targetPath: $(Build.Repository.LocalPath)/server/out
      - script: "node client/node_modules/vscode/bin/test"
        displayName: "run tests"
        env:
          CODE_TESTS_PATH: $(Build.Repository.LocalPath)/client/out/test
          CODE_TESTS_WORKSPACE: $(Build.Repository.LocalPath)/client/src/e2e
          CODE_DISABLE_EXTENSIONS: true

  - job: macOS
    dependsOn: Build
    pool:
      name: Hosted macOS
      demands: npm
    steps:
      - task: NodeTool@0
        displayName: "Use Node 10"
        inputs:
          versionSpec: 10.x
      - task: Npm@1
        displayName: "Install dev dependencies"
        inputs:
          verbose: false
      - task: Npm@1
        displayName: "Install client dependencies"
        inputs:
          verbose: false
          workingDir: client
      - task: Npm@1
        displayName: "Install server dependencies"
        inputs:
          verbose: false
          workingDir: server
      - task: DownloadPipelineArtifact@0
        inputs:
          artifactName: "GherkinEditor"
          targetPath: $(Build.Repository.LocalPath)/client/out
      - task: DownloadPipelineArtifact@0
        inputs:
          artifactName: "GherkinServer"
          targetPath: $(Build.Repository.LocalPath)/server/out
      - script: "node client/node_modules/vscode/bin/test"
        displayName: "run tests"
        env:
          CODE_TESTS_PATH: $(Build.Repository.LocalPath)/client/out/test
          CODE_TESTS_WORKSPACE: $(Build.Repository.LocalPath)/client/src/e2e
          CODE_DISABLE_EXTENSIONS: true

  - job: Linux
    dependsOn: Build
    pool:
      name: Hosted Ubuntu 1604
      demands: npm
    steps:
      - task: NodeTool@0
        displayName: "Use Node 10"
        inputs:
          versionSpec: 10.x
      - task: Npm@1
        displayName: "Install dev dependencies"
        inputs:
          verbose: false
      - task: Npm@1
        displayName: "Install client dependencies"
        inputs:
          verbose: false
          workingDir: client
      - task: Npm@1
        displayName: "Install server dependencies"
        inputs:
          verbose: false
          workingDir: server
      - task: DownloadPipelineArtifact@0
        inputs:
          artifactName: "GherkinEditor"
          targetPath: $(Build.Repository.LocalPath)/client/out
      - task: DownloadPipelineArtifact@0
        inputs:
          artifactName: "GherkinServer"
          targetPath: $(Build.Repository.LocalPath)/server/out
      - script: |
          set -e
          /usr/bin/Xvfb :10 -ac >> /tmp/Xvfb.out 2>&1 &
          disown -ar
        displayName: "start xvfb"
      - script: "node client/node_modules/vscode/bin/test"
        displayName: "run tests"
        env:
          DISPLAY: :10
          CODE_TESTS_PATH: $(Build.Repository.LocalPath)/client/out/test
          CODE_TESTS_WORKSPACE: $(Build.Repository.LocalPath)/client/src/e2e
          CODE_DISABLE_EXTENSIONS: true

  - job: Publish
    dependsOn:
      - Windows
      - macOS
      - Linux
    pool:
      name: Hosted Ubuntu 1604
      demands: npm
    steps:
      - task: NodeTool@0
        displayName: "Use Node 10"
        inputs:
          versionSpec: 10.x
      - task: DownloadPipelineArtifact@0
        inputs:
          artifactName: "GherkinEditor"
          targetPath: $(Build.Repository.LocalPath)/client/out
      - task: DownloadPipelineArtifact@0
        inputs:
          artifactName: "GherkinServer"
          targetPath: $(Build.Repository.LocalPath)/server/out
      - script: |
          npm i vsce --no-save
        displayName: "npm install vsce tooling"
        env:
          NPM_TOKEN: $(NPMTOKEN)

      - script: |
          npm run release:ci
        displayName: "release"
        env:
          NPM_TOKEN: $(NPMTOKEN)
          GITHUB_TOKEN: $(GITHUBTOKEN)
          PAT: $(AZUREDEVOPSTOKEN)
