# Node.js
# Build a general Node.js application with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/javascript

pool:
  vmImage: "Ubuntu 16.04"

steps:
  - script: |
      npm ci
      cd client
      npm ci
      cd ../server
      npm ci
      cd ..
    displayName: "npm install dependencies"
    env:
      NPM_TOKEN: $(NPMTOKEN)

  - script: |
      npm run build
    displayName: "build"
    env:
      NPM_TOKEN: $(NPMTOKEN)

  - script: |
      set -e
      /usr/bin/Xvfb :10 -ac >> /tmp/Xvfb.out 2>&1 &
      disown -ar
    displayName: "start xvfb"

  - script: "node node_modules/vscode/bin/test"
    displayName: "run tests"
    env:
      DISPLAY: 10

  - script: |
      npm i vsce --no-save
    displayName: "npm install tooling"
    env:
      NPM_TOKEN: $(NPMTOKEN)

  - script: |
      npm run release:ci
    displayName: "release"
    env:
      NPM_TOKEN: $(NPMTOKEN)
      GITHUB_TOKEN: $(GITHUBTOKEN)
      PAT: $(AZUREDEVOPSTOKEN)
