# Node.js
# Build a general Node.js application with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/javascript

pool:
  vmImage: 'Ubuntu 16.04'

steps:

- script: |
    npm i -g vsce
    npm ci
    cd client
    npm ci
    node ./node_modules/vscode/bin/install
    cd ../server
    npm ci
    cd ..
    npm run build
  displayName: 'npm install and build'

- task: CopyFiles@2
  inputs:
    SourceFolder: $(System.DefaultWorkingDirectory)
    Contents: |
      *.md
      !vsc-extension-quickstart.md
      .vscodeignore
      media/*.*
    TargetFolder: $(System.DefaultWorkingDirectory)/dist

- script: |
      cd ./dist/client
      npm ci
      cd ../server
      npm ci
      cd ../..
  displayName: 'install production dependencies in dist'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(System.DefaultWorkingDirectory)/dist/**/*.*'
    artifactName: 'bddPowerTools'
